# Generated by Django 4.0.4 on 2022-04-21 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('P_image', models.ImageField(default='', upload_to='')),
                ('P_price', models.FloatField()),
                ('P_name', models.CharField(max_length=30)),
            ],
        ),
    ]
